apiVersion: apps/v1
kind: Deployment
metadata:  
  name: nodejs-deployment  
  labels:    
    app: helloworld
spec:  
  replicas: 1  
  selector:    
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec: 
     containers:
      - name: helloworld
        image: rj:rj
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    app: helloworld
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8081
    nodePort: 32121
  selector:
    app: helloworld
